app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_security import login_required, roles_required
from app.utils import get_country_data, transfer_money, get_filtered_customers, get_order_by_column
from app.forms import AddCustomerForm, AddAccountForm, EditCustomerForm, TransferForm
from datetime import datetime, timedelta, date
from .models import db, Customer, Account, Transaction, TransactionOperation, TransactionType, AccountType, Role, User, roles_users
import numpy as np
from collections import Counter
from sqlalchemy import  func


main_bp = Blueprint("main", __name__)


# Login route

@main_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()

        if not user:
            flash("User not found. Check your email.", "danger")
        elif not user.verify_password(password): 
            flash("Incorrect password. Please try again.", "danger")
        else:
            flash("Login successful!", "success")
            return redirect(url_for("main.startpage"))

    return render_template("security/login_user.html")

# Logout route
@main_bp.route('/logout')
@login_required
def logout():
    
    return redirect(url_for('main.logout'))




#Dashboard Route (index)

    
    
@main_bp.route("/", methods=["GET"])
@login_required
def startpage():
    
    
    
    country = request.args.get("country", "all")
    country_data = get_country_data(country)
    
    richest_customers_by_country = country_data["richest_customers"]
    total_customers_by_country = country_data["total_customers"]
    total_accounts_by_country = country_data["total_accounts"]
    transactions_by_country = country_data["transactions"]
    

    labels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    balance_data_rich = [customer["total_balance"] for customer in country_data["richest_customers"]]
     
    main_bar_color =["#5641f5"]*11
    off_bar_color = ["#b5a3d9"]*11
    maxrange = np.arange(1, 11).tolist()
    

    transaction_data_operation = [t["operation"] for t in country_data["transactions"]]
    transaction_data_new_balance = [t["new_balance"] for t in country_data["transactions"]]
    transaction_by_date = [t["date"].weekday() for t in country_data["transactions"]]
    transaction_by_month = [t["date"].month for t in country_data["transactions"]]
    income_by_month = [t["operation"] for t in country_data["transactions"]]
    
    transaction_data_amount = [t["amount"] for t in country_data["transactions"]]
    country_list_items = sorted(set(db.session.execute(db.select(Customer.country)).scalars().all()))
    

    counter = Counter(transaction_by_date)
    iterations_per_week = dict(sorted(counter.items()))
    
    counter_month = Counter(transaction_by_month)
    iterations_per_month = dict(sorted(counter_month.items()))
    
    counter_income_by_month = Counter(income_by_month)
   

    average_transactions_list = []
    for i in iterations_per_month.values():
        
        average_transactions_list.append(i)
 
    balance_list = []
    balance = db.session.execute(db.select(Account.balance)).scalars()
    
    for bal in balance:
        balance_list.append(bal)
    
    balance_sum = sum(balance_list)
    
    cust_list = []
    cust_amount = db.session.execute(db.select(Customer)).scalars().all()
    customer_amount = len(cust_amount)
     
    
    today = date.today()
    yesterday = today - timedelta(days = 4)
    day_before_yesterday = yesterday - timedelta(days = 1)
    week_ago = today - timedelta(days = 7)
    
  
    latest_transactions = Transaction.query.order_by(Transaction.date.desc()).all()
 
 
    return render_template("index.html",
                           balance_sum=balance_sum,
                           customer_amount=customer_amount,
                           richest_customers_by_country=richest_customers_by_country,
                           total_customers_by_country=total_customers_by_country,
                           total_accounts_by_country=total_accounts_by_country,
                           transactions_by_country=transactions_by_country,
                           country_list_items=country_list_items,
                           selected_country=country,
                           balance_data_rich=balance_data_rich,
                           transaction_data_amount=transaction_data_amount,
                           transaction_data_operation=transaction_data_operation,
                           transaction_data_new_balance=transaction_data_new_balance,
                           labels=labels,
                           main_bar_color=main_bar_color,
                           maxrange=maxrange,
                           off_bar_color=off_bar_color,
                           iterations_per_week=iterations_per_week,
                           iterations_per_month=iterations_per_month,
                           average_transactions_list=average_transactions_list,
                           latest_transactions=latest_transactions,
                           now=datetime.now()
                           )



# Management routes

@main_bp.route("/management", methods=["GET", "POST"])
@login_required
def management():
    sort_order = request.args.get('sort_order', 'asc')
    sort_column = request.args.get('sort_by', 'id')
    search_word = request.args.get('q', '')
    
    page = request.args.get("page", 1, type=int)
    per_page = 50

    search_customers = get_filtered_customers(search_word)


    order_by = get_order_by_column(sort_column, sort_order)

    all_customers = search_customers.order_by(order_by).all()

    customers_pagination = search_customers.order_by(order_by).paginate(page=page, per_page=per_page, error_out=False)

    customer_pag = customers_pagination.items
    has_more = customers_pagination.has_next

    


    if request.headers.get("X-Requested-With") == "XMLHttpRequest":
        return jsonify([
            {
                "id": cust.id,
                "name": f"{cust.given_name} {cust.surname}",
                "email": cust.email_address,
                "address": f"{cust.streetaddress}, {cust.zipcode}",
                "city": cust.city,
                "national_id": cust.national_id
            } for cust in customer_pag 
        ])


    customer_amount = search_customers.count()
    acc_amount = db.session.query(db.func.count(Account.id)).join(Customer, Customer.id == Account.customer_id).scalar()

    return render_template("management.html", customer_amount=customer_amount, acc_amount=acc_amount, all_customers=all_customers, q=search_word,customer_pag=customer_pag, has_more=has_more)




@main_bp.route("/management/customers", methods=["GET"])
def load_more_customers():
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 50, type=int)
    sort_order = request.args.get('sort_order', 'asc')
    sort_column = request.args.get('sort_by', 'id')
    search_word = request.args.get('q', '')

    search_customers = get_filtered_customers(search_word)

    order_by = get_order_by_column(sort_column, sort_order)


    customers_pagination = search_customers.order_by(order_by).paginate(page=page, per_page=per_page, error_out=False)

    customers = [
        {
            "id": cust.id,
            "name": f"{cust.given_name} {cust.surname}",
            "email": cust.email_address,
            "address": f"{cust.streetaddress}, {cust.zipcode}",
            "city": cust.city,
            "national_id": cust.national_id
        }
        for cust in customers_pagination.items
    ]

    return jsonify({
        "customers": customers,
        "has_more": customers_pagination.has_next,
        "next_page": page + 1
    })



# Customer routes




@main_bp.route("/edit_customer", methods=["GET", "POST"])
@login_required
def edit_customer():
    customer_id = request.args.get("id")
    customer = db.get_or_404(Customer, customer_id)
    form = EditCustomerForm(obj=customer)
    
    if form.validate_on_submit():
        form.populate_obj(customer)
        db.session.commit()
        
        flash("Account successfully edited!")
        return redirect(url_for("main.management"))
    return render_template("edit_customer.html", form=form, customer=customer)



    

@main_bp.route("/customer/<int:id>", methods=["GET", "POST"])
@login_required
def customer_list(id):
    

    customer = Customer.query.get_or_404(id)
    selected_account_id = request.args.get("account_id", None, type=int)
    customer_accounts = customer.accounts  
    account_dict = {acc.id: acc for acc in customer_accounts} 
    

    if not selected_account_id and customer_accounts:
        selected_account_id = customer_accounts[0].id


    
    account_balances = {}

    customer_transaction_count = (
    Transaction.query
    .join(Account, Transaction.account_id == Account.id)
    .filter(Account.customer_id == customer.id)
    .with_entities(func.count(Transaction.id))
    .scalar()
    )

    customer_debit_count = (
        Transaction.query
        .join(Account, Transaction.account_id == Account.id)
        .filter(Account.customer_id == customer.id, Transaction.type == "DEBIT")
        .with_entities(func.count(Transaction.id))
        .scalar()
    )

    customer_credit_count = (
        Transaction.query
        .join(Account, Transaction.account_id == Account.id)
        .filter(Account.customer_id == customer.id, Transaction.type == "CREDIT")
        .with_entities(func.count(Transaction.id))
        .scalar()
    )


    customer_credit_sum = (
        Transaction.query
        .join(Account, Transaction.account_id == Account.id)
        .filter(Account.customer_id == customer.id, Transaction.type == "CREDIT")

app/templates/customer.html
{% extends 'baseTemplate.html' %}
{% set active_page = "management" %}
{% block title %}{% endblock %}

{% block content %}

<div class="container-fluid mt-3">
    <div class="row g-3">
        <div class="col-md-4">
            <div class="card">
                <div class="row d-flex justify-content-between">
                    <div class="col card-title pb-4 mb-3">Total Balance</div>

                    
                </div>
                <div class="row d-flex align-items-center mb-4">
                    <div
                        class="col-2 cvv-col ms-3 d-flex justify-content-center align-items-center">
                        <span id="cvvbal">CVV</span>
                    </div>
                    <div class="col-2 mt-0 ms-4" id="dots">••••</div>
                    <div class="col-2">{{ customer.national_id[-4:] }}</div>
                </div>

                <div class="col display-3 pb-3" id="total-balance">
                    <span class="green-details">$</span><span class>
                        {%- if total_balance >= 1000000000 -%}
                        {{ "{:,.2f}B".format(total_balance / 1000000000) }}
                        {%- elif total_balance >= 1000000 -%}
                        {{ "{:,.3f}M".format(total_balance / 1000000) }}
                        {%- else -%}
                        {{ "{:,.2f}".format(total_balance) }}
                        {%- endif -%}
                    </span>
                </div>

                <div class="col mt-0 pt-0">

                    <div class="col card-details pb-4">All Accounts ({{
                        total_accounts }})<strong
                            class="cardBold">
                            <div
                                class="table-container table-container-customer">
                                <table class="wealt-table text-start">
                                    {% for acc in customer_accounts %}
                                    <tbody>

                                        <tr
                                            class="{% if acc.id == selected_account_id %}text-white{% else %}{% endif %}"
                                            onclick="window.location='{{ url_for('main.customer_list', id=customer.id, account_id=acc.id, page=1) }}';"
                                            style="cursor: pointer;">

                                            <td>{{ acc.account_type.value
                                                }}</td>
                                            <td class="text-end">$ {%- if
                                                acc.balance >= 1000000000 -%}
                                                {{ "{:,.2f}B".format(acc.balance
                                                /
                                                1000000000) }}
                                                {%- elif acc.balance >= 1000000
                                                -%}
                                                {{ "{:,.3f}M".format(acc.balance
                                                /
                                                1000000) }}
                                                {%- else -%}
                                                {{ "{:,.2f}".format(acc.balance)
                                                }}
                                                {%- endif -%}</td>

                                        </tr>
                                    </tbody>
                                    {% endfor %}
                                </table>
                            </div>
                        </strong>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="row d-flex justify-content-between">
                    <div class="col card-title pb-4">Transactions</div>
                    

                </div>
                <div class="table-container table-container-big flex-grow-1">
                    {% if transactions %}
                    <table class="table wealt-table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Date</th>
                                <th>Type</th>
                                <th>Amount</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="transaction-table">
                            {% for t in transactions %}
                            <tr>
                                <td>{{ t.id }}</td>
                                <td>{% if t.date.strftime("%d %b, %Y") == today
                                    %}Today{% else
                                    %}{{t.date.strftime("%d %b")}}{%endif%}</td>
                                <td>{{ t.operation.value }}</td>
                                <td
                                    class="text-end {% if t.type.value == 'Debit' %}text-success{% else %}text-danger{% endif %}">{%
                                    if t.type.value == 'Debit' %}{% else %}-{%
                                    endif %} ${{ "{:,.2f}".format(t.amount)
                                    }}</td>
                                <td></td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <p>No transactions found for this account.</p>
                            {% endif %}
                        </tbody>
                    </table>
                    <div class="text-center mt-3 me-5">
                        <button id="load-more-btn" class="btn"
                            onclick="loadMoreTransactions()" {% if not has_more
                            %}style="display: none;" {% endif %}>
                            View More
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card">
                <div class="row d-flex justify-content-between">
                    <div class="col card-title pb-4">Account</div>
                    <div class="col text-end">
                        <div class="dropdown">
                            <a class="add_acc_btn"
                                href="{{ url_for('main.add_account', customer_id=customer.id) }}">
                                <i
                                    class="bi bi-plus-lg py-1 px-2 tiny-buttons rounded"></i>
                            </a>
                            
                            
                        </div>
                    </div>
                </div>

                <div class="information">
                </div>
                <div class="row mt-1 text-center">
                    <div>
                        <canvas id="barChart"></canvas>
                    </div>
                    <div class="col-6 green-details">

                        <span>$</span>
                        <span>
                            {% if customer_debit_sum %}
                            {%- if customer_debit_sum >= 1000000000 -%}
                            {{ "{:,.2f}B".format(customer_debit_sum /
                            1000000000) }}
                            {%- elif customer_debit_sum >= 1000000 -%}
                            {{ "{:,.3f}M".format(customer_debit_sum / 1000000)
                            }}
                            {%- else -%}
                            {{ "{:,.2f}".format(customer_debit_sum) }}
                            {%- endif -%}
                            {% else %}
                            {{ "0.00"|float }}
                            {% endif %}
                        </span>
                    </div>
                    <div class="col-6 red-details">{{ customer_credit_count }}
                        <span>$</span><span class>
                            {% if customer_credit_sum %}
                            {%- if customer_credit_sum >= 1000000000 -%}
                            {{ "{:,.2f}B".format(customer_credit_sum /
                            1000000000) }}
                            {%- elif customer_credit_sum >= 1000000 -%}
                            {{ "{:,.3f}M".format(customer_credit_sum / 1000000)
                            }}
                            {%- else -%}
                            {{ "{:,.2f}".format(customer_credit_sum) }}
                            {%- endif -%}
                            {% else %}
                            {{ "0.00"|float }}
                            {% endif %}
                        </span></div>
                </div>




                </div>
            </div>

            <div class="col-md-6">
                <div class="card">

                    <div class="row d-flex justify-content-between">
                        <div class="col card-title pb-2">
                            Customer Information
                        </div>
                        <div class="col text-end">
                            <form id="searchForm" method="GET" onsubmit="return updateAction()">
                                <label for="search">Enter Customer ID:</label>
                                <input type="number" id="search" name="id" min="1" max="{{ customer_amount }}">
                                <button type="submit">Search</button>
                            </form>
                            
                            
                            
                            
                            </div>
                    </div>
    
                    <div class="row">
                        <div class="col-md-3">
                            <h6 class="text-muted">Personal Details</h6>
                            <p><strong>Name:</strong> {{ customer.given_name|title }} {{ customer.surname|title }}</p>
                            <p><strong>Birthday:</strong> {{ customer.birthday.strftime('%Y-%m-%d') }}</p>
                            <p><strong>National ID:</strong> {{ customer.national_id }}</p>
                        </div>
                
                        <div class="col-md-5">
                            <h6 class="text-muted">Location</h6>
                            <p><strong>Country:</strong> {{ customer.country|title }}, {{ customer.country_code|upper }}</p>
                            <p><strong>City:</strong> {{ customer.city|title }}, {{ customer.zipcode }}</p>
                            <p><strong>Address:</strong> {{ customer.streetaddress|title }}</p>
                        </div>
                
                        <div class="col-md-4">
                            <h6 class="text-muted">Contact</h6>
                            <p><strong>Email:</strong> 
                                <a href="mailto:{{ customer.email_address }}" class="text-light">{{ customer.email_address|lower }}</a>
                            </p>
                            <p><strong>Phone:</strong> 
                                <a href="tel:+{{ customer.telephone_country_code }}{{ customer.telephone }}" class="text-light">
                                    {{ customer.telephone_country_code }} {{ customer.telephone }}
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            
        </div>
    </div>
</div><script>
    const MAX_CUSTOMER_ID = {{ customer_amount }};

    function updateAction() {
        const searchInput = document.getElementById('search');
        const searchValue = parseInt(searchInput.value, 10);

        if (!searchValue || searchValue < 1) {
            alert("Please enter a valid customer ID (1 or higher).");
            return false;
        }

        if (searchValue > MAX_CUSTOMER_ID) {
            alert("The entered ID exceeds the maximum customer ID: " + MAX_CUSTOMER_ID);
            return false;
        }

        window.location.href = "{{ url_for('main.customer_list', id=0) }}".replace('0', searchValue);
        return false;
    }
</script>

    <script id="barChartData" type="application/json">
    {
        "labels": ["Income", "Expenses"],
        "datasets": [
            {
                "data": [{{customer_debit_sum if customer_debit_sum else e}}, {{customer_credit_sum if customer_credit_sum else 0}}],
                "backgroundColor": ["#02c56f", "#c71400"],
                "borderRadius": 6
            }
        ]
    }
</script>

    {% endblock %}

app/templates/management.html
{% extends 'baseTemplate.html' %}
{% set active_page = "management" %}
{% block title %}Management{% endblock %}

{% block content %}



<div class="container-fluid mt-3">
    <div class="row g-3">
        
        <div class="col-md">
            <div class="card h-100">
                <div class="row d-flex justify-content-between">
                    <div class="col card-title pb-2">Manage Customers</div>
                    <div class="col text-end">
                        <a class="add_acc_btn" href="{{ url_for('main.add_customer') }}">
                            <i class="bi bi-plus-lg py-1 px-2 tiny-buttons rounded"> Create New</i>
                        </a>
                    </div>
                </div>
    
                <div class="managedash">
                    <div class="row mt-3">
                        <div class="col-3 p-0">
                            <input type="text" id="search" placeholder=" Search customers.." class="p-0 ms-2 w-100" value="{{ q }}">
                        </div>
                    </div>
    
                    <div class="table-container-full table-container mt-2">
                        <table class="wealt-table table-hover table text-start">
                            <thead>
                                <tr>
                                    <th scope="col" class="text-start">
                                        <a href="#" onclick="updateSorting('customer', event)">
                                            <i id="customer-sort-icon" class=""></i> Customer
                                        </a>
                                    </th>
                                    <th scope="col" class="text-start">
                                        <a href="#" onclick="updateSorting('address', event)">
                                            <i id="address-sort-icon" class=""></i> Address
                                        </a>
                                    </th>
                                    <th scope="col" class="text-start">
                                        <a href="#" onclick="updateSorting('city', event)">
                                            <i id="city-sort-icon" class=""></i> City
                                        </a>
                                    </th>
                                    <th scope="col" class="text-start">
                                        <a href="#" onclick="updateSorting('national_id', event)">
                                            <i id="national_id-sort-icon" class=""></i> National ID
                                        </a>
                                    </th>
                                    <th scope="col" class="text-start">
                                        <a href="#" onclick="updateSorting('id', event)">
                                            <i id="id-sort-icon" class=""></i> #
                                        </a>
                                    </th>
                                </tr>
                            </thead>
                            
                            
                            <tbody id="customer-table">{% for cust in customer_pag %}
                                <tr onclick="window.location='{{ url_for('main.customer_list', id=cust.id) }}';" style="cursor: pointer;">
                                    
                                    <td class="text-start"><strong>{{ cust.given_name|title }} {{ cust.surname|title }}</strong><br>
                                        <span style="font-size: 0.85em; color: gray;">{{ cust.email_address|lower }}</span>
                                    </td>
                                    <td class="text-start">{{ cust.streetaddress|title }}, {{ cust.zipcode }}</td>
                                    <td class="text-start">{{ cust.city|title }}</td>
                                    <td class="text-start">{{ cust.national_id }}</td>
                                    <td class="text-start">{{ cust.id }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="text-center mt-3">
                            <button id="load-more-btn" class="btn" onclick="loadMoreCustomers()" 
                                {% if not has_more %}style="display: none;"{% endif %}>
                                View More
                            </button>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>

        

            
                </div>
            </div>
        </div>

    </div>
</div>






<script>
let currentSortColumn = "id";
let currentSortOrder = "asc";
let currentSearch = "";
function fetchCustomers() {
    currentSearch = document.getElementById("search").value;
    let loadMoreBtn = document.getElementById("load-more-btn");

    if (currentSearch.length > 0) {
        loadMoreBtn.style.display = "none";
    } else {
        loadMoreBtn.style.display = "block"; 
        loadMoreBtn.style.margin = "20px auto"; 
        loadMoreBtn.style.textAlign = "center";
    }

    updateTable();
}


function updateSorting(column, event) {
    if (event) event.preventDefault(); 

    if (currentSortColumn === column) {
        currentSortOrder = currentSortOrder === "asc" ? "desc" : "asc";
    } else {
        currentSortColumn = column;
        currentSortOrder = "asc";
    }

    updateTable();
    updateSortIcons(); 
}


function updateSortIcons() {
    document.querySelectorAll("th a i").forEach(icon => {
        icon.className = ""; 
    });

    let icon = document.querySelector(`#${currentSortColumn}-sort-icon`);
    if (icon) {
        icon.className = currentSortOrder === "asc" ? "bi bi-arrow-up" : "bi bi-arrow-down";
    }
}

function updateTable() {
    fetch(`/management?q=${currentSearch}&sort_by=${currentSortColumn}&sort_order=${currentSortOrder}`, {
        headers: { "X-Requested-With": "XMLHttpRequest" }
    })
    .then(response => response.json())
    .then(data => {
        let tableBody = document.getElementById("customer-table");
        tableBody.innerHTML = "";

        if (data.length === 0) {
            tableBody.innerHTML = `<tr><td colspan="5" class="text-center">No customers found</td></tr>`;
            return;
        }

        data.forEach(cust => {
            let row = `
                <tr onclick="window.location='/customer/${cust.id}';" style="cursor: pointer;">
                    <td class="text-start"><strong>${cust.name}</strong><br>
                        <span style="font-size: 0.85em; color: gray;">${cust.email}</span>
                    </td>
                    <td class="text-start">${cust.address}</td>
                    <td class="text-start">${cust.city}</td>
                    <td class="text-start">${cust.national_id}</td>
                    <td class="text-start">${cust.id}</td>
                </tr>
            `;
            tableBody.innerHTML += row;
        });
    })
    .catch(error => {
        console.error("Error fetching customers:", error);
        document.getElementById("customer-table").innerHTML =
            `<tr><td colspan="5" class="text-center">Error loading data</td></tr>`;
    });
}




document.getElementById("search").addEventListener("input", fetchCustomers);
</script>
<script>
    let currentPage = 2;

function loadMoreCustomers() {
    fetch(`/management/customers?page=${currentPage}&sort_by=${currentSortColumn}&sort_order=${currentSortOrder}&q=${currentSearch}`)
    .then(response => response.json())
    .then(data => {
        if (data.customers.length > 0) {
            let table = document.getElementById("customer-table");

            data.customers.forEach(c => {
                let row = table.insertRow();
                row.innerHTML = `
    <td class="text-start"><strong>${c.name}</strong><br>
        <span style="font-size: 0.85em; color: gray;">${c.email}</span>
    </td>
    <td class="text-start">${c.address}</td>
    <td class="text-start">${c.city}</td>
    <td class="text-start">${c.national_id}</td>
    <td class="text-start">${c.id}</td>
`;

                row.style.cursor = "pointer";
                row.onclick = function() {
                    window.location.href = `/customer/${c.id}`;
                };
            });

            if (!data.has_more) {
                document.getElementById("load-more-btn").style.display = "none";
            } else {
                currentPage++;
            }
        }
    })
    .catch(error => console.error("Error loading more customers:", error));
}

</script>




{% endblock %}